version: '2'
services:
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=group_8
    ports:
      - 5432:5432
    volumes:
      - "./.pgdata:/var/lib/postgresql/data"
